// Code generated by "stringer -type=DeviceClass"; DO NOT EDIT.

package legohat

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[Light-1]
	_ = x[TiltSensor-2]
	_ = x[MotionSensor-3]
	_ = x[ColorDistanceSensor-4]
	_ = x[ColorSensor-5]
	_ = x[DistanceSensor-6]
	_ = x[ForceSensor-7]
	_ = x[Matrix-8]
	_ = x[Motor-9]
}

const _DeviceClass_name = "UnknownLightTiltSensorMotionSensorColorDistanceSensorColorSensorDistanceSensorForceSensorMatrixMotor"

var _DeviceClass_index = [...]uint8{0, 7, 12, 22, 34, 53, 64, 78, 89, 95, 100}

func (i DeviceClass) String() string {
	if i < 0 || i >= DeviceClass(len(_DeviceClass_index)-1) {
		return "DeviceClass(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DeviceClass_name[_DeviceClass_index[i]:_DeviceClass_index[i+1]]
}
