// Code generated by "stringer -type=DeviceClass -linecomment"; DO NOT EDIT.

package legohat

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[Internal-1]
	_ = x[Light-2]
	_ = x[TiltSensor-3]
	_ = x[MotionSensor-4]
	_ = x[ColorDistanceSensor-5]
	_ = x[ColorSensor-6]
	_ = x[DistanceSensor-7]
	_ = x[ForceSensor-8]
	_ = x[Matrix-9]
	_ = x[Motor-10]
}

const _DeviceClass_name = "UnknownInternalLightTiltSensorMotionSensorColorDistanceSensorColorSensorDistanceSensorForceSensorMatrixMotor"

var _DeviceClass_index = [...]uint8{0, 7, 15, 20, 30, 42, 61, 72, 86, 97, 103, 108}

func (i DeviceClass) String() string {
	if i < 0 || i >= DeviceClass(len(_DeviceClass_index)-1) {
		return "DeviceClass(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DeviceClass_name[_DeviceClass_index[i]:_DeviceClass_index[i+1]]
}
